version: "3"
services:
  db:
    image: postgres
    env_file:
      - docker.env
    volumes:
      - data-volume:/var/lib/db
    ports:
      - "5432:5432"
    expose:
      - "5432"
  api:
    build: .
    env_file:
      - docker.env
    image: testbuild
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  data-volume:
