# Generated by Django 2.1.3 on 2019-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefirmwarefinalversion',
            name='distribution_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sefirmwarefinalversion',
            name='exclude_by_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
